<a href="https://colab.research.google.com/github/divyanshisachdeva/ML/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System specification

because these were system commands we preceeded with ! (exclamation mark )

In [ ]:
 !cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
!cat /proc/meminfo

MemTotal:       13290460 kB
MemFree:         7567904 kB
MemAvailable:   12169984 kB
Buffers:          375892 kB
Cached:          4377076 kB
SwapCached:            0 kB
Active:           659320 kB
Inactive:        4724584 kB
Active(anon):       1344 kB
Inactive(anon):   631352 kB
Active(file):     657976 kB
Inactive(file):  4093232 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               376 kB
Writeback:             0 kB
AnonPages:        630960 kB
Mapped:           309812 kB
Shmem:              1752 kB
KReclaimable:     176276 kB
Slab:             219288 kB
SReclaimable:     176276 kB
SUnreclaim:        43012 kB
KernelStack:        5840 kB
PageTables:        11312 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6645228 kB
Committed_AS:    2817536 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12168 kB
VmallocChunk:    

In [ ]:
!pip install pandas


In [ ]:
import pandas as pd
df=pd.read_csv("/content/breast_cancer_data (1).csv")
print(df.head())

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

In [ ]:
!ls

'breast_cancer_data (1).csv'   sample_data


In [ ]:
l=[12,"aman","male",165.73,12]
t=(1,"ram","male",168,90,1)
s={4,"female",165.98,4}
print(l)
print(t)
print(s)


[12, 'aman', 'male', 165.73, 12]
(1, 'ram', 'male', 168, 90, 1)
{4, 165.98, 'female'}


In [ ]:
l=[12,"aman","male",165.73]
l[0]=8
l.append("hello")
print(l)

[8, 'aman', 'male', 165.73, 'hello']


In [ ]:
t=(1,"ram","male",168,90)
t[0:2]
t[0]="amamn"

TypeError: 'tuple' object does not support item assignment

In [ ]:
s={4,"female",165.98,4,4,4,4,4}
print(s)


{4, 165.98, 'female'}


In [ ]:
a=False
b=0
print(a==b)
print(a is b)



True
False


In [ ]:
age=int(input("enter your age "))
if (age>=18):
  print("yay a voter ")
else :
  print("cant vote ")

enter your age 90
yay a voter 


if elif


In [ ]:
a= int(input("enter no"))
b= int(input("enter no"))
c= int(input("enter no"))

if (a<b>c):
  print(b,"is the greatest ")
elif(b<a>c):
   print(a,"is the greatest ")
else:
   print(c,"is the greatest ")

enter no23
enter no23
enter no23
23 is the greatest 


In [ ]:
#factorial

def func(num):
  num=int(input("enter no."))
  fact=1
  if num==0:
    print(1)
  else:
    for i in range (1,num+1):
      fact=fact*i
    return fact

print(func(5))

enter no.4
24


In [ ]:
def fact(x):
  if (x==0):
    return 1
  else:
    return x*fact(x-1)
fact(5)

120

In [ ]:
import numpy as np
l=[1,"hellp",3,4]
a=np.array(l)
print(a)
type(a)

['1' 'hellp' '3' '4']


numpy.ndarray

In [ ]:
import numpy as np
a= np.array([[1,2,34,45],[12,34,56,75]],dtype=float)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 1.  2. 34. 45.]
 [12. 34. 56. 75.]]
(2, 4)
2
8


In [ ]:
import numpy as np
zero=np.zeros((4,5))
print(zero)
one=np.ones((3,3))
print(one)
all=np.full((3,3),5)
print(all)
identity=np.eye(3)
print(identity)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import  numpy as np
exam=np.random.random((3,4))# all values will be between 0 and 1
print(exam)
#within a range
a=np.random.randint(1,10,(3,3))# values from 1 to 9
print(a)
#evenly spaced --> no. of values
b = np .linspace(10,100,7)
print(b)
#evenly spaced --> step
c=np.arange(10,100,7)
print(c)

[[0.25923714 0.90181175 0.23028996 0.23793813]
 [0.01497527 0.32704386 0.73640939 0.41685191]
 [0.65946341 0.05792805 0.1094656  0.6457695 ]]
[[5 9 5]
 [2 8 1]
 [5 5 8]]
[ 10.  25.  40.  55.  70.  85. 100.]
[10 17 24 31 38 45 52 59 66 73 80 87 94]


In [ ]:
import numpy as np
l=[1,2,3,4]
a=np.asarray(l)
print(a)


[1 2 3 4]


In [ ]:
import numpy as np
a= np.array ([[1,2,3,4],[2,3,4,5]])
b=np.array([[4,5,6,7],[1,2,3,4]])
print(a)
print(b)
print(a+b)
print(np.add(a,b))
print(a-b)
print(np.subtract(a,b))
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b))
print(np.transpose(a))
print(b.T)
#reshape
print(a.reshape(4,2))

[[1 2 3 4]
 [2 3 4 5]]
[[4 5 6 7]
 [1 2 3 4]]
[[ 5  7  9 11]
 [ 3  5  7  9]]
[[ 5  7  9 11]
 [ 3  5  7  9]]
[[-3 -3 -3 -3]
 [ 1  1  1  1]]
[[-3 -3 -3 -3]
 [ 1  1  1  1]]
[[ 4 10 18 28]
 [ 2  6 12 20]]
[[ 4 10 18 28]
 [ 2  6 12 20]]
[[0.25       0.4        0.5        0.57142857]
 [2.         1.5        1.33333333 1.25      ]]
[[0.25       0.4        0.5        0.57142857]
 [2.         1.5        1.33333333 1.25      ]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[[4 1]
 [5 2]
 [6 3]
 [7 4]]
[[1 2]
 [3 4]
 [2 3]
 [4 5]]
